### PR TITLE
Offset times to count for timezone

### LINKED ISSUE #403: Fix wrong times in rentals
When renting items, the date generated seems to be in UTC 0, which results in an incorrect date if you make a rental after 8pm EST.

Since the day of the rental is automatically added, it is impossible to make a rental with a return date of tomorrow after 8pm (because the start date will be the day after and the server returns an error that rentals cannot have the same start and end date).

### PR DESCRIPTION
**Pull request by emroussel**
Closes #403

### CODE REVIEW

File: src/pages/rental-details/rental-details.ts [hunk 1]
```diff
@@ -33,8 +33,11 @@ export class RentalDetailsPage {
   ngOnInit() {
     this.items = this.itemsService.getItems();
 
+    // We need to offset the date by the difference between the user's timezone
+    // and UTC 0 to have an accurate date
     let tomorrow = new Date();
-    tomorrow.setDate((new Date()).getDate() + 1);
+    const offset = tomorrow.getTimezoneOffset() / (60 * 24);
```
Comment (AdamVig) [inline src/pages/rental-details/rental-details.ts]: I think this should be abstracted into either a helper function or a property on the component, since the same offset is used in both `ngOnInit` and `onRent`. It would be more efficient to calculate it once.

File: src/pages/rental-details/rental-details.ts [hunk 2]
```diff
@@ -33,8 +33,11 @@ export class RentalDetailsPage {
...
+    tomorrow.setDate((new Date()).getDate() - offset + 1);
```
Comment (AdamVig) [inline src/pages/rental-details/rental-details.ts]: Instead of instantiating a `new Date()` for the `.getDate()`, I would reuse `tomorrow`:
```JavaScript
tomorrow.setDate(tomorrow.getDate() - offset + 1);
```

File: src/pages/rental-details/rental-details.ts [hunk 3]
```diff
@@ -51,10 +54,16 @@ export class RentalDetailsPage {
    */
   onRent() {
     if (this.rentalForm.valid) {
+      // We need to offset the date by the difference between the user's timezone
+      // and UTC 0 to have an accurate date
+      let today = new Date();
+      const offset = today.getTimezoneOffset() / (60 * 24);
+      today.setDate((new Date()).getDate() - offset);
```
Comment (AdamVig) [inline src/pages/rental-details/rental-details.ts]: Same as the above suggestion, I would replace this line with:
```JavaScript
today.setDate(today.getDate() - offset);
```
